 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/charts", type: :request do
  # Chart. As you add validations to Chart, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Chart.create! valid_attributes
      get charts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      chart = Chart.create! valid_attributes
      get chart_url(chart)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_chart_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      chart = Chart.create! valid_attributes
      get edit_chart_url(chart)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Chart" do
        expect {
          post charts_url, params: { chart: valid_attributes }
        }.to change(Chart, :count).by(1)
      end

      it "redirects to the created chart" do
        post charts_url, params: { chart: valid_attributes }
        expect(response).to redirect_to(chart_url(Chart.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Chart" do
        expect {
          post charts_url, params: { chart: invalid_attributes }
        }.to change(Chart, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post charts_url, params: { chart: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chart" do
        chart = Chart.create! valid_attributes
        patch chart_url(chart), params: { chart: new_attributes }
        chart.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the chart" do
        chart = Chart.create! valid_attributes
        patch chart_url(chart), params: { chart: new_attributes }
        chart.reload
        expect(response).to redirect_to(chart_url(chart))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        chart = Chart.create! valid_attributes
        patch chart_url(chart), params: { chart: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested chart" do
      chart = Chart.create! valid_attributes
      expect {
        delete chart_url(chart)
      }.to change(Chart, :count).by(-1)
    end

    it "redirects to the charts list" do
      chart = Chart.create! valid_attributes
      delete chart_url(chart)
      expect(response).to redirect_to(charts_url)
    end
  end
end
